PATCHES = [
 (2, "The main avenue, Broadway, had been", "The main avenue, the Long Mile, had been"),
 (2, "\"Four months,\" Vane said, as if the number were a physical weight he had dropped on the table. \"We have four weeks.\"", "\"A year,\" Vane said, as if the number were a physical weight he had dropped on the table. \"We have forty days.\""),
 (2, "And I will assign one of my own students to assist your team.", "And the Lord Chancellor has asked that one of his protégés assist your team."),
 (3, "If a barge travels three miles upstream against a tide of one mile per hour, and the water flows at two miles per hour, how long does it take to reach a lock that is five miles away?", "A barge makes three miles an hour in still water and must go upstream, against a current of two miles an hour, to a lock five miles away. How long does the trip take?"),
 (3, "The barge moves at three miles per hour relative to the water, but the water moves at two miles per hour downstream. The net speed upstream is one mile per hour. Five miles at one mile per hour is five hours.", "The barge moves at three miles an hour through the water, but the water carries it back at two. The net speed upstream is one mile an hour. Five miles at one mile an hour is five hours."),
 (4, "the King’s taxes", "the Queen’s taxes"),
 (6, "a vector that pointed to the center of the universe, or at least, the center of the galaxy.", "a vector that pointed along the axis on which the whole sky turns."),
 (7, "\"We have thirty miles to go. And the sun is not done with us.\"", "\"We have most of a mile to go. And the sun is not done with us.\""),
 (7, "flat and commandant", "flat and commanding"),
 (7, "Mags, who had been sitting on a rock, looked up, her blue scarf bright against the pale dust. \"So we subtract?\"\n\n\"Subtract,\" Isla said. \"The expansion is small, but it is there. We have to account for it.\"", "Mags, who had been sitting on a rock, looked up, her blue scarf bright against the pale dust. \"So we add a little?\"\n\n\"Add,\" Isla said. \"A hot chain is longer than its marks say, so each pull covers more ground than we credit it. The expansion is small, but it is there. We have to account for it.\""),
 (8, "We would be here until the heat death of the universe.", "We would be here until the world wore out."),
 (8, "\"Forty-five, thirty, twelve,\" she said.", "\"Fifty-seven, thirty, twelve,\" she said."),
 (8, "Isla calculated it. The sum of the angles in a triangle is always one hundred and eighty degrees. She had measured two. The third was implied.", "The sum of the angles in a triangle is always one hundred and eighty degrees. She had measured two from the baseline; Joss and Mags carried the sightglass out to the red flag, and she read the third from there."),
 (8, "\"Forty-nine, twenty-nine, forty-eight,\" she said softly.", "\"Eighty, nineteen, forty-eight,\" she said softly."),
 (11, "The mule, which Mags had christened Sergeant Major, stood", "The mule, Ledger, stood"),
 (11, "There were four hundred and twelve links in the chain, and no one had counted them yet.", "There were a hundred links to every chain, and no one had counted them since Vell."),
 (13, "In the dead of winter, in the middle of the Unmade, an orchard", "Out of season, in the middle of the Unmade, an orchard"),
 (13, "\"We are one hundred and twelve people,\" she said. \"We have been cut off from the kingdom. We have no tax, no post, no road. We are living in a gap in the map.\"", "\"You are one hundred and twelve people,\" she said. \"You have been cut off from the kingdom. No tax, no post, no road. You are living in a gap in the map.\""),
 (15, "\"My grandmother said the same thing,\" he murmured", "\"Hester said the same thing,\" he murmured"),
 (15, "\"This is where my grandmother put her first station,\"", "\"This is where Hester put her first station,\""),
 (15, "But they agree with my grandmother’s work.", "But they agree with my great-grandmother’s work."),
 (15, "My grandmother knew it. She did not trust their center.", "Hester knew it. She did not trust their center."),
 (15, "And what is the point, Master Quillon?", "And what is the point, Miss Quillon?"),
 (16, "It is a feature, Miss Corrin, not a bug.", "It is a feature of the plan, Miss Corrin, not a flaw in it."),
 (18, "Wynne, the miller, walked beside them with the weary pride of a man", "The miller walked beside them with the weary pride of a man"),
 (18, "\"The wheel is gone,\" Wynne said, his voice dry.", "\"The wheel is gone,\" the miller said, his voice dry."),
 (18, "Wynne looked at her sharply.", "The miller looked at her sharply."),
 (18, "Enough to turn a wheel until the heat death of the universe, if you ask a bridge-wright.", "Enough to turn a wheel until the sun goes out, if you ask a bridge-wright."),
 (18, "The ratio was almost exactly one foot of fall for every thousand feet of distance.", "The river fell about one foot in every hundred and sixteen, a torrent’s slope, far too steep for a channel that meant to keep its banks."),
 (18, "That’s the gradient for a canal that stays put.", "That’s the gradient for a race that stays put, so we make the water walk the long way round and keep the fall for the wheel."),
 (19, "The orchard stood in a tangle of bare limbs, skeletal against the grey sky, while the ground below lay littered with the brown, rotting remains of apples picked weeks ago.", "The orchard stood thick with leaf under the grey sky, its blossom long since gone to small green fruit, while the ground below lay littered with fallen petals and the odd windfall."),
 (20, "That is a discrepancy of ninety links. That is nearly four hundred feet.", "That is a discrepancy of ninety links. That is nearly sixty feet."),
 (20, "Ninety links. Four hundred feet.", "Ninety links. Sixty feet."),
 (20, "a closure of one in two hundred and fifty thousand", "a closure of one in fifty thousand"),
 (21, "a woman who had been dead for seventy years", "a woman who had been dead for twenty years"),
 (22, "\"Three hundred and twelve links,\" he shouted", "\"Four hundred and fifty links,\" he shouted"),
 (22, "But by the honest sharing of a mistake, by the careful, patient work", "But by the careful, patient work"),
 (23, "Old Mrs. Gable, the schoolmistress from Ennis Vale", "Wynne, the schoolmistress from Ennis Vale"),
 (23, "\"Over sixty-three miles.\"", "\"Over forty-one miles.\""),
 (23, "But over sixty-three miles, across", "But over forty-one miles, across"),
 (0, "seventy years", "forty-four years"),
 (0, "Seventy years", "Forty-four years"),
]
